# Generated by Django 2.0.2 on 2018-10-05 20:23

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_leave_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='jumbotron_bgcolor',
            field=models.CharField(default='#eeeeee', max_length=7, validators=[pages.models.layout_validator]),
        ),
        migrations.AddField(
            model_name='page',
            name='jumbotron_textcolor',
            field=models.CharField(default='#000000', max_length=7, validators=[pages.models.layout_validator]),
        ),
    ]
